version: '3'
services:
  reverse-proxy: 
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080 #Management UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#Webserver on port 8000
  webserver1:
    image: nobody1997/nginx-tutorial:1.0.0  
    labels: 
      - "traefik.http.routers.webserver1.rule=Host(`your-domain-here`)"
      - "traefik.http.services.webserver1.loadbalancer.server.port=8000"
